/* soapClient.cpp
   Generated by gSOAP 2.8.83 for C:\Users\YYu\Documents\LR\release-2020\WebService\gsoap\gsoap_2.8.83\gsoap-2.8\gsoap\mod_gsoap\gsoap_win\isapi\vs2010\samples\dime\dime.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.cpp ver 2.8.83 2019-05-22 06:45:07 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__getImage(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *name, xsd__base64Binary &image)
{	if (soap_send_ns__getImage(soap, soap_endpoint, soap_action, name) || soap_recv_ns__getImage(soap, image))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns__getImage(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *name)
{	struct ns__getImage soap_tmp_ns__getImage;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost/gsoap/mod_gsoap.dll?dime";
	soap_tmp_ns__getImage.name = name;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns__getImage(soap, &soap_tmp_ns__getImage);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__getImage(soap, &soap_tmp_ns__getImage, "ns:getImage", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__getImage(soap, &soap_tmp_ns__getImage, "ns:getImage", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns__getImage(struct soap *soap, xsd__base64Binary &image)
{
	struct ns__getImageResponse *soap_tmp_ns__getImageResponse;
	image.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ns__getImageResponse = soap_get_ns__getImageResponse(soap, NULL, "ns:getImageResponse", NULL);
	if (!soap_tmp_ns__getImageResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	image = soap_tmp_ns__getImageResponse->image;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__putImage(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *name, xsd__base64Binary *image, int &status)
{	if (soap_send_ns__putImage(soap, soap_endpoint, soap_action, name, image) || soap_recv_ns__putImage(soap, status))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns__putImage(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *name, xsd__base64Binary *image)
{	struct ns__putImage soap_tmp_ns__putImage;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost/gsoap/mod_gsoap.dll?dime";
	soap_tmp_ns__putImage.name = name;
	soap_tmp_ns__putImage.image = image;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns__putImage(soap, &soap_tmp_ns__putImage);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__putImage(soap, &soap_tmp_ns__putImage, "ns:putImage", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__putImage(soap, &soap_tmp_ns__putImage, "ns:putImage", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns__putImage(struct soap *soap, int &status)
{
	struct ns__putImageResponse *soap_tmp_ns__putImageResponse;
	soap_default_int(soap, &status);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ns__putImageResponse = soap_get_ns__putImageResponse(soap, NULL, "ns:putImageResponse", NULL);
	if (!soap_tmp_ns__putImageResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	status = soap_tmp_ns__putImageResponse->status;
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.cpp */
